package entities;
// Generated 26-09-2016 11:01:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * InstitucionSalud generated by hbm2java
 */
@Entity
@Table(name="institucion_salud"
    ,catalog="sigf_v1"
)
public class InstitucionSalud  implements java.io.Serializable {


     private Integer idInstitucionSalud;
     private String nombreInstitucionSalud;
     private Set<Trabajador> trabajadors = new HashSet<Trabajador>(0);

    public InstitucionSalud() {
    }

	
    public InstitucionSalud(String nombreInstitucionSalud) {
        this.nombreInstitucionSalud = nombreInstitucionSalud;
    }
    public InstitucionSalud(String nombreInstitucionSalud, Set<Trabajador> trabajadors) {
       this.nombreInstitucionSalud = nombreInstitucionSalud;
       this.trabajadors = trabajadors;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_institucion_salud", unique=true, nullable=false)
    public Integer getIdInstitucionSalud() {
        return this.idInstitucionSalud;
    }
    
    public void setIdInstitucionSalud(Integer idInstitucionSalud) {
        this.idInstitucionSalud = idInstitucionSalud;
    }

    
    @Column(name="nombre_institucion_salud", nullable=false)
    public String getNombreInstitucionSalud() {
        return this.nombreInstitucionSalud;
    }
    
    public void setNombreInstitucionSalud(String nombreInstitucionSalud) {
        this.nombreInstitucionSalud = nombreInstitucionSalud;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="institucionSalud")
    public Set<Trabajador> getTrabajadors() {
        return this.trabajadors;
    }
    
    public void setTrabajadors(Set<Trabajador> trabajadors) {
        this.trabajadors = trabajadors;
    }




}


