package entities;
// Generated 26-09-2016 11:01:55 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MaeGuias generated by hbm2java
 */
@Entity
@Table(name="mae_guias"
    ,catalog="sigf_v1"
)
public class MaeGuias  implements java.io.Serializable {


     private Integer idMaeGuias;
     private String folio;
     private Date fechaGuia;
     private Date fechaRecaudacion;
     private String bus;
     private String unidad;
     private String codigoConductor;
     private String codigoGarita;
     private String codigoLinea;
     private int idEstado;
     private Integer idProcesoRecaudacion;
     private Integer totalIngresos;
     private Integer totalEgresos;
     private int viajeEspecial;
     private int otrosIngresos;
     private Integer saldo;
     private int numeroVueltas;
     private String turno;
     private char observacion;
     private int recaudada;
     private Integer administracion;
     private Integer combustible;
     private Integer boletos;
     private int nochero;
     private Integer licitacion;
     private Integer aseo;
     private Integer taller;
     private Integer varios1;
     private Integer varios2;
     private Integer deficit;
     private Integer ahorro;
     private Integer imposicion;
     private Integer anticipo;

    public MaeGuias() {
    }

	
    public MaeGuias(int idEstado, int viajeEspecial, int otrosIngresos, int numeroVueltas, char observacion, int recaudada, int nochero) {
        this.idEstado = idEstado;
        this.viajeEspecial = viajeEspecial;
        this.otrosIngresos = otrosIngresos;
        this.numeroVueltas = numeroVueltas;
        this.observacion = observacion;
        this.recaudada = recaudada;
        this.nochero = nochero;
    }
    public MaeGuias(String folio, Date fechaGuia, Date fechaRecaudacion, String bus, String unidad, String codigoConductor, String codigoGarita, String codigoLinea, int idEstado, Integer idProcesoRecaudacion, Integer totalIngresos, Integer totalEgresos, int viajeEspecial, int otrosIngresos, Integer saldo, int numeroVueltas, String turno, char observacion, int recaudada, Integer administracion, Integer combustible, Integer boletos, int nochero, Integer licitacion, Integer aseo, Integer taller, Integer varios1, Integer varios2, Integer deficit, Integer ahorro, Integer imposicion, Integer anticipo) {
       this.folio = folio;
       this.fechaGuia = fechaGuia;
       this.fechaRecaudacion = fechaRecaudacion;
       this.bus = bus;
       this.unidad = unidad;
       this.codigoConductor = codigoConductor;
       this.codigoGarita = codigoGarita;
       this.codigoLinea = codigoLinea;
       this.idEstado = idEstado;
       this.idProcesoRecaudacion = idProcesoRecaudacion;
       this.totalIngresos = totalIngresos;
       this.totalEgresos = totalEgresos;
       this.viajeEspecial = viajeEspecial;
       this.otrosIngresos = otrosIngresos;
       this.saldo = saldo;
       this.numeroVueltas = numeroVueltas;
       this.turno = turno;
       this.observacion = observacion;
       this.recaudada = recaudada;
       this.administracion = administracion;
       this.combustible = combustible;
       this.boletos = boletos;
       this.nochero = nochero;
       this.licitacion = licitacion;
       this.aseo = aseo;
       this.taller = taller;
       this.varios1 = varios1;
       this.varios2 = varios2;
       this.deficit = deficit;
       this.ahorro = ahorro;
       this.imposicion = imposicion;
       this.anticipo = anticipo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_mae_guias", unique=true, nullable=false)
    public Integer getIdMaeGuias() {
        return this.idMaeGuias;
    }
    
    public void setIdMaeGuias(Integer idMaeGuias) {
        this.idMaeGuias = idMaeGuias;
    }

    
    @Column(name="folio", length=7)
    public String getFolio() {
        return this.folio;
    }
    
    public void setFolio(String folio) {
        this.folio = folio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_guia", length=10)
    public Date getFechaGuia() {
        return this.fechaGuia;
    }
    
    public void setFechaGuia(Date fechaGuia) {
        this.fechaGuia = fechaGuia;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_recaudacion", length=10)
    public Date getFechaRecaudacion() {
        return this.fechaRecaudacion;
    }
    
    public void setFechaRecaudacion(Date fechaRecaudacion) {
        this.fechaRecaudacion = fechaRecaudacion;
    }

    
    @Column(name="bus", length=11)
    public String getBus() {
        return this.bus;
    }
    
    public void setBus(String bus) {
        this.bus = bus;
    }

    
    @Column(name="unidad", length=1)
    public String getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(String unidad) {
        this.unidad = unidad;
    }

    
    @Column(name="codigo_conductor", length=4)
    public String getCodigoConductor() {
        return this.codigoConductor;
    }
    
    public void setCodigoConductor(String codigoConductor) {
        this.codigoConductor = codigoConductor;
    }

    
    @Column(name="codigo_garita", length=2)
    public String getCodigoGarita() {
        return this.codigoGarita;
    }
    
    public void setCodigoGarita(String codigoGarita) {
        this.codigoGarita = codigoGarita;
    }

    
    @Column(name="codigo_linea", length=4)
    public String getCodigoLinea() {
        return this.codigoLinea;
    }
    
    public void setCodigoLinea(String codigoLinea) {
        this.codigoLinea = codigoLinea;
    }

    
    @Column(name="id_estado", nullable=false)
    public int getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(int idEstado) {
        this.idEstado = idEstado;
    }

    
    @Column(name="id_proceso_recaudacion")
    public Integer getIdProcesoRecaudacion() {
        return this.idProcesoRecaudacion;
    }
    
    public void setIdProcesoRecaudacion(Integer idProcesoRecaudacion) {
        this.idProcesoRecaudacion = idProcesoRecaudacion;
    }

    
    @Column(name="total_ingresos")
    public Integer getTotalIngresos() {
        return this.totalIngresos;
    }
    
    public void setTotalIngresos(Integer totalIngresos) {
        this.totalIngresos = totalIngresos;
    }

    
    @Column(name="total_egresos")
    public Integer getTotalEgresos() {
        return this.totalEgresos;
    }
    
    public void setTotalEgresos(Integer totalEgresos) {
        this.totalEgresos = totalEgresos;
    }

    
    @Column(name="viaje_especial", nullable=false)
    public int getViajeEspecial() {
        return this.viajeEspecial;
    }
    
    public void setViajeEspecial(int viajeEspecial) {
        this.viajeEspecial = viajeEspecial;
    }

    
    @Column(name="otros_ingresos", nullable=false)
    public int getOtrosIngresos() {
        return this.otrosIngresos;
    }
    
    public void setOtrosIngresos(int otrosIngresos) {
        this.otrosIngresos = otrosIngresos;
    }

    
    @Column(name="saldo")
    public Integer getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(Integer saldo) {
        this.saldo = saldo;
    }

    
    @Column(name="numero_vueltas", nullable=false)
    public int getNumeroVueltas() {
        return this.numeroVueltas;
    }
    
    public void setNumeroVueltas(int numeroVueltas) {
        this.numeroVueltas = numeroVueltas;
    }

    
    @Column(name="turno", length=1)
    public String getTurno() {
        return this.turno;
    }
    
    public void setTurno(String turno) {
        this.turno = turno;
    }

    
    @Column(name="observacion", nullable=false, length=1)
    public char getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(char observacion) {
        this.observacion = observacion;
    }

    
    @Column(name="recaudada", nullable=false)
    public int getRecaudada() {
        return this.recaudada;
    }
    
    public void setRecaudada(int recaudada) {
        this.recaudada = recaudada;
    }

    
    @Column(name="administracion")
    public Integer getAdministracion() {
        return this.administracion;
    }
    
    public void setAdministracion(Integer administracion) {
        this.administracion = administracion;
    }

    
    @Column(name="combustible")
    public Integer getCombustible() {
        return this.combustible;
    }
    
    public void setCombustible(Integer combustible) {
        this.combustible = combustible;
    }

    
    @Column(name="boletos")
    public Integer getBoletos() {
        return this.boletos;
    }
    
    public void setBoletos(Integer boletos) {
        this.boletos = boletos;
    }

    
    @Column(name="nochero", nullable=false)
    public int getNochero() {
        return this.nochero;
    }
    
    public void setNochero(int nochero) {
        this.nochero = nochero;
    }

    
    @Column(name="licitacion")
    public Integer getLicitacion() {
        return this.licitacion;
    }
    
    public void setLicitacion(Integer licitacion) {
        this.licitacion = licitacion;
    }

    
    @Column(name="aseo")
    public Integer getAseo() {
        return this.aseo;
    }
    
    public void setAseo(Integer aseo) {
        this.aseo = aseo;
    }

    
    @Column(name="taller")
    public Integer getTaller() {
        return this.taller;
    }
    
    public void setTaller(Integer taller) {
        this.taller = taller;
    }

    
    @Column(name="varios1")
    public Integer getVarios1() {
        return this.varios1;
    }
    
    public void setVarios1(Integer varios1) {
        this.varios1 = varios1;
    }

    
    @Column(name="varios2")
    public Integer getVarios2() {
        return this.varios2;
    }
    
    public void setVarios2(Integer varios2) {
        this.varios2 = varios2;
    }

    
    @Column(name="deficit")
    public Integer getDeficit() {
        return this.deficit;
    }
    
    public void setDeficit(Integer deficit) {
        this.deficit = deficit;
    }

    
    @Column(name="ahorro")
    public Integer getAhorro() {
        return this.ahorro;
    }
    
    public void setAhorro(Integer ahorro) {
        this.ahorro = ahorro;
    }

    
    @Column(name="imposicion")
    public Integer getImposicion() {
        return this.imposicion;
    }
    
    public void setImposicion(Integer imposicion) {
        this.imposicion = imposicion;
    }

    
    @Column(name="anticipo")
    public Integer getAnticipo() {
        return this.anticipo;
    }
    
    public void setAnticipo(Integer anticipo) {
        this.anticipo = anticipo;
    }




}


