package entities;
// Generated 26-09-2016 11:01:55 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Movimientos generated by hbm2java
 */
@Entity
@Table(name="movimientos"
    ,catalog="sigf_v1"
)
public class Movimientos  implements java.io.Serializable {


     private Integer idBus;
     private Integer bus;
     private String unidad;
     private String cargo;
     private Double monto;

    public Movimientos() {
    }

    public Movimientos(Integer bus, String unidad, String cargo, Double monto) {
       this.bus = bus;
       this.unidad = unidad;
       this.cargo = cargo;
       this.monto = monto;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_bus", unique=true, nullable=false)
    public Integer getIdBus() {
        return this.idBus;
    }
    
    public void setIdBus(Integer idBus) {
        this.idBus = idBus;
    }

    
    @Column(name="Bus")
    public Integer getBus() {
        return this.bus;
    }
    
    public void setBus(Integer bus) {
        this.bus = bus;
    }

    
    @Column(name="Unidad", length=1)
    public String getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(String unidad) {
        this.unidad = unidad;
    }

    
    @Column(name="Cargo", length=50)
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }

    
    @Column(name="Monto", precision=22, scale=0)
    public Double getMonto() {
        return this.monto;
    }
    
    public void setMonto(Double monto) {
        this.monto = monto;
    }




}


