package entities;
// Generated 26-09-2016 11:01:55 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ServicioProcesoRecaudacion generated by hbm2java
 */
@Entity
@Table(name="servicio_proceso_recaudacion"
    ,catalog="sigf_v1"
)
public class ServicioProcesoRecaudacion  implements java.io.Serializable {


     private Integer idServicioProcesoRecaudacion;
     private ProcesoRecaudacion procesoRecaudacion;
     private Servicio servicio;

    public ServicioProcesoRecaudacion() {
    }

    public ServicioProcesoRecaudacion(ProcesoRecaudacion procesoRecaudacion, Servicio servicio) {
       this.procesoRecaudacion = procesoRecaudacion;
       this.servicio = servicio;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_servicio_proceso_recaudacion", unique=true, nullable=false)
    public Integer getIdServicioProcesoRecaudacion() {
        return this.idServicioProcesoRecaudacion;
    }
    
    public void setIdServicioProcesoRecaudacion(Integer idServicioProcesoRecaudacion) {
        this.idServicioProcesoRecaudacion = idServicioProcesoRecaudacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_proceso_recaudacion", nullable=false)
    public ProcesoRecaudacion getProcesoRecaudacion() {
        return this.procesoRecaudacion;
    }
    
    public void setProcesoRecaudacion(ProcesoRecaudacion procesoRecaudacion) {
        this.procesoRecaudacion = procesoRecaudacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_servicio", nullable=false)
    public Servicio getServicio() {
        return this.servicio;
    }
    
    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }




}


