/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.util.Date;

/**
 *
 * @author ianfr
 */
public class DinerosRecaudadosView extends javax.swing.JPanel {

    /**
     * Creates new form DinerosRecaudadosView
     */
    public DinerosRecaudadosView() {
        initComponents();
        this.fechaDate.setDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fechaDate = new com.toedter.calendar.JDateChooser();
        viewButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Dineros Recaudados x Fecha"));

        jLabel1.setText("Fecha: ");

        viewButton.setText("Ver");

        printButton.setText("Imprimir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fechaDate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printButton)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(viewButton)
                        .addComponent(printButton))
                    .addComponent(fechaDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(243, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser fechaDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton printButton;
    private javax.swing.JButton viewButton;
    // End of variables declaration//GEN-END:variables

    public com.toedter.calendar.JDateChooser getFechaDate() {
        return fechaDate;
    }

    public javax.swing.JButton getPrintButton() {
        return printButton;
    }

    public javax.swing.JButton getViewButton() {
        return viewButton;
    }
}
