/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.AhorroConductorController;
import controllers.AportePatronalController;
import controllers.CajaCompensacionController;
import controllers.ConductoresSinContratoController;
import controllers.CreditoSaludController;
import controllers.DetalleAbonosController;
import controllers.DetalleCargosController;
import controllers.DetalleISTController;
import controllers.DetalleLiquidacionBusFlotaController;
import controllers.DiasTrabajadosConductorController;
import controllers.DinerosRecaudadosController;
import controllers.DistribucionCargasFamiliaresController;
import controllers.DistribucionSindicatosController;
import controllers.DistribucionTerminalController;
import controllers.DistribucionTerminalNegativosController;
import controllers.ISTController;
import controllers.ImposicionesConductorController;
import controllers.LiquidacionBusController;
import controllers.LiquidacionDinamicaController;
import controllers.LiquidacionSolyMarController;
import controllers.LiquidacionTerminalController;
import controllers.LiquidacionVinaBusController;
import controllers.MemoCargasFamiliaresController;
import controllers.MesSelectorController;
import controllers.PlanillonDescuentosController;
import controllers.ProcesoGeneralController;
import controllers.ProcesoRecaudacionController;
import controllers.ProduccionBusController;
import controllers.ProduccionConductorController;
import controllers.ProduccionFlotaController;
import controllers.ProduccionFlotaUnidadController;
import controllers.ReconocimientoDeudasController;
import controllers.RetencionJudicialController;
import controllers.SISController;
import controllers.SaldoAnteriorController;
import controllers.SaldosMasLiquidacionFlotaController;
import controllers.SaldosMasLiquidacionFlotaSolyMarController;
import controllers.SaldosProduccionFlotaController;
import controllers.SaldosProduccionFlotaControllerSolyMar;
import controllers.SeguroCesantiaDosPuntoCuatroController;
import controllers.SeguroCesantiaTresController;
import controllers.SeguroController;
import controllers.SeguroInteramericaController;
import controllers.TerceraHojaController;
import controllers.VoucherCargasFamiliaresController;
import dao.Conexion;
import java.io.InputStream;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JSplitPane;
import javax.swing.JTabbedPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author ianfr
 */
public class ReporterVBView extends javax.swing.JFrame {

    /**
     * Creates new form ReporterVBView
     */
    public ReporterVBView() {
        initComponents();
        this.splitPane.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        tabbedPane = new javax.swing.JTabbedPane();
        reportTabbedPane = new javax.swing.JTabbedPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        extrasMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        guiasMenu = new javax.swing.JMenu();
        correccionMenuItem = new javax.swing.JMenuItem();
        dineroRecaudadosMenuItem = new javax.swing.JMenuItem();
        dinerosXProcesosMenuItem = new javax.swing.JMenuItem();
        conductoresMenu = new javax.swing.JMenu();
        produccionConductorMenuItem = new javax.swing.JMenuItem();
        diasTrabajadosConductorMenuItem = new javax.swing.JMenuItem();
        cincoPorcientoMenuItem = new javax.swing.JMenuItem();
        ahorroConductorMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        busesMenu = new javax.swing.JMenu();
        produccionBusMenuItem = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        flotasMenu = new javax.swing.JMenu();
        produccionFlotaMenuItem = new javax.swing.JMenuItem();
        bonosFlotasMenuItem = new javax.swing.JMenuItem();
        produccionFlotaUnidadMenuItem = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        remuneracionesMenu = new javax.swing.JMenu();
        planillonImposicionMenuItem = new javax.swing.JMenuItem();
        planillonDescuentosMenuItem = new javax.swing.JMenuItem();
        conductoresSinContratoMenuItem = new javax.swing.JMenuItem();
        descuentoMenu = new javax.swing.JMenu();
        errorCodigoMenuItem = new javax.swing.JMenuItem();
        segundasImposicionesMenuItem = new javax.swing.JMenuItem();
        deudasMenuItem = new javax.swing.JMenuItem();
        retencionJudicialMenuItem = new javax.swing.JMenuItem();
        saldoAnteriorMenuItem = new javax.swing.JMenuItem();
        cajaMenuItem = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        cargasFamiliaresMenuItem = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        sisMenuItem = new javax.swing.JMenuItem();
        istMenuItem = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        aportePatronalMenuItem = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        seguroCesantiaMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        flotaUnidadTres = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        splitPane.setMinimumSize(new java.awt.Dimension(300, 300));
        splitPane.setPreferredSize(new java.awt.Dimension(300, 300));

        tabbedPane.setMinimumSize(new java.awt.Dimension(150, 150));
        splitPane.setTopComponent(tabbedPane);
        splitPane.setRightComponent(reportTabbedPane);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Archivo");

        extrasMenu.setMnemonic('h');
        extrasMenu.setText("Extras");

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Acerca de ..");
        extrasMenu.add(aboutMenuItem);

        fileMenu.add(extrasMenu);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        guiasMenu.setMnemonic('e');
        guiasMenu.setText("Guías");

        correccionMenuItem.setMnemonic('t');
        correccionMenuItem.setText("Corrección");
        correccionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correccionMenuItemActionPerformed(evt);
            }
        });
        guiasMenu.add(correccionMenuItem);

        dineroRecaudadosMenuItem.setText("Dineros Recaudados");
        dineroRecaudadosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dineroRecaudadosMenuItemActionPerformed(evt);
            }
        });
        guiasMenu.add(dineroRecaudadosMenuItem);

        dinerosXProcesosMenuItem.setText("Dineros x Proceso");
        dinerosXProcesosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dinerosXProcesosMenuItemActionPerformed(evt);
            }
        });
        guiasMenu.add(dinerosXProcesosMenuItem);

        menuBar.add(guiasMenu);

        conductoresMenu.setText("Conductores");

        produccionConductorMenuItem.setText("Producción ");
        produccionConductorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produccionConductorMenuItemActionPerformed(evt);
            }
        });
        conductoresMenu.add(produccionConductorMenuItem);

        diasTrabajadosConductorMenuItem.setText("Días Trabajados");
        diasTrabajadosConductorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diasTrabajadosConductorMenuItemActionPerformed(evt);
            }
        });
        conductoresMenu.add(diasTrabajadosConductorMenuItem);

        cincoPorcientoMenuItem.setText("5 % + Anticipo");
        cincoPorcientoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoPorcientoMenuItemActionPerformed(evt);
            }
        });
        conductoresMenu.add(cincoPorcientoMenuItem);

        ahorroConductorMenuItem.setText("Ahorro");
        ahorroConductorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ahorroConductorMenuItemActionPerformed(evt);
            }
        });
        conductoresMenu.add(ahorroConductorMenuItem);
        conductoresMenu.add(jSeparator1);

        jMenuItem13.setText("Liquidación x Terminal");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        conductoresMenu.add(jMenuItem13);

        jMenuItem18.setText("Tercera Hoja");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        conductoresMenu.add(jMenuItem18);

        jMenuItem20.setText("Listado General de Conductores");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        conductoresMenu.add(jMenuItem20);

        jMenuItem25.setText("Liquidaciones");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        conductoresMenu.add(jMenuItem25);

        menuBar.add(conductoresMenu);

        busesMenu.setText("Buses");

        produccionBusMenuItem.setText("Producción");
        produccionBusMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produccionBusMenuItemActionPerformed(evt);
            }
        });
        busesMenu.add(produccionBusMenuItem);

        jMenuItem2.setText("Listado");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        busesMenu.add(jMenuItem2);

        menuBar.add(busesMenu);

        flotasMenu.setText("Flotas");

        produccionFlotaMenuItem.setText("Producción ");
        produccionFlotaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produccionFlotaMenuItemActionPerformed(evt);
            }
        });
        flotasMenu.add(produccionFlotaMenuItem);

        bonosFlotasMenuItem.setText("Bonos");
        flotasMenu.add(bonosFlotasMenuItem);

        produccionFlotaUnidadMenuItem.setText("Producción x Unidad");
        produccionFlotaUnidadMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produccionFlotaUnidadMenuItemActionPerformed(evt);
            }
        });
        flotasMenu.add(produccionFlotaUnidadMenuItem);

        jMenuItem8.setText("Detalle Bus x Flota");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        flotasMenu.add(jMenuItem8);

        menuBar.add(flotasMenu);

        remuneracionesMenu.setText("Remuneraciones");

        planillonImposicionMenuItem.setText("Planillón Imposiciones");
        planillonImposicionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planillonImposicionMenuItemActionPerformed(evt);
            }
        });
        remuneracionesMenu.add(planillonImposicionMenuItem);

        planillonDescuentosMenuItem.setText("Planillón Descuentos ");
        planillonDescuentosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planillonDescuentosMenuItemActionPerformed(evt);
            }
        });
        remuneracionesMenu.add(planillonDescuentosMenuItem);

        conductoresSinContratoMenuItem.setText("Conductores Sin Contrato ");
        conductoresSinContratoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conductoresSinContratoMenuItemActionPerformed(evt);
            }
        });
        remuneracionesMenu.add(conductoresSinContratoMenuItem);

        descuentoMenu.setText("Descuentos");

        errorCodigoMenuItem.setText("Error de Código");
        descuentoMenu.add(errorCodigoMenuItem);

        segundasImposicionesMenuItem.setText("Segundos Contratos");
        descuentoMenu.add(segundasImposicionesMenuItem);

        deudasMenuItem.setText("Reconocimientos Deudas");
        deudasMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deudasMenuItemActionPerformed(evt);
            }
        });
        descuentoMenu.add(deudasMenuItem);

        retencionJudicialMenuItem.setText("Retención Judicial");
        retencionJudicialMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retencionJudicialMenuItemActionPerformed(evt);
            }
        });
        descuentoMenu.add(retencionJudicialMenuItem);

        saldoAnteriorMenuItem.setText("Saldos Anteriores ");
        saldoAnteriorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoAnteriorMenuItemActionPerformed(evt);
            }
        });
        descuentoMenu.add(saldoAnteriorMenuItem);

        cajaMenuItem.setText("Cajas Compensación");
        cajaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaMenuItemActionPerformed(evt);
            }
        });
        descuentoMenu.add(cajaMenuItem);

        jMenuItem22.setText("Metlife");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        descuentoMenu.add(jMenuItem22);

        jMenuItem23.setText("Interamericana");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        descuentoMenu.add(jMenuItem23);

        jMenuItem24.setText("Crédito Salud");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        descuentoMenu.add(jMenuItem24);

        remuneracionesMenu.add(descuentoMenu);

        jMenu4.setText("Memos");

        jMenuItem5.setText("Cargas Familiares");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        remuneracionesMenu.add(jMenu4);

        jMenu5.setText("Distribuciones");

        cargasFamiliaresMenuItem.setText("Voucher Cargas Familiares");
        cargasFamiliaresMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargasFamiliaresMenuItemActionPerformed(evt);
            }
        });
        jMenu5.add(cargasFamiliaresMenuItem);

        jMenuItem17.setText("Cargas Familiares");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem17);

        jMenuItem14.setText("Sindicatos");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem14);

        jMenuItem15.setText("Liquidaciones Positivas");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem15);

        jMenuItem16.setText("Liquidaciones Negativas");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem16);

        sisMenuItem.setText("SIS");
        sisMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sisMenuItemActionPerformed(evt);
            }
        });
        jMenu5.add(sisMenuItem);

        istMenuItem.setText("IST Grupal");
        istMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                istMenuItemActionPerformed(evt);
            }
        });
        jMenu5.add(istMenuItem);

        jMenuItem19.setText("Detalle IST");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem19);

        aportePatronalMenuItem.setText("Aporte Patronal");
        aportePatronalMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aportePatronalMenuItemActionPerformed(evt);
            }
        });
        jMenu5.add(aportePatronalMenuItem);

        jMenuItem11.setText("Seguro Cesantía 3,0 ");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem11);

        seguroCesantiaMenuItem.setText("Seguro Cesantía 2,4");
        seguroCesantiaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seguroCesantiaMenuItemActionPerformed(evt);
            }
        });
        jMenu5.add(seguroCesantiaMenuItem);

        remuneracionesMenu.add(jMenu5);

        menuBar.add(remuneracionesMenu);

        jMenu1.setText("Tesorería");

        jMenuItem3.setText("Saldos x Flota x Unidad");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Liquidación x Bus");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem12.setText("Detalle Liquidación Bus x Flota");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem12);

        jMenuItem1.setText("Saldos + Liquidación");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenu2.setText("Movimientos");

        jMenuItem10.setText("Detalle x Abonos");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuItem9.setText("Detalle x Cargos");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenu1.add(jMenu2);

        jMenu3.setText("Unidad 3");

        flotaUnidadTres.setText("Saldos x Flota Unidad 3");
        flotaUnidadTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flotaUnidadTresActionPerformed(evt);
            }
        });
        jMenu3.add(flotaUnidadTres);

        jMenuItem21.setText("Liquidación x Flota Unidad 3");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem21);

        jMenu1.add(jMenu3);

        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void planillonImposicionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planillonImposicionMenuItemActionPerformed
        this.mesSelectorView = new MesSelectorView();
        MesSelectorController controller = new MesSelectorController(this.mesSelectorView, this);
        setNewTab(this.mesSelectorView, "Planillón Imposiciones");
    }//GEN-LAST:event_planillonImposicionMenuItemActionPerformed

    private void istMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_istMenuItemActionPerformed
        this.mesSelectorView = new MesSelectorView();
        ISTController controller = new ISTController(this.mesSelectorView, this);
        setNewTab(this.mesSelectorView, "IST Grupal");
    }//GEN-LAST:event_istMenuItemActionPerformed

    private void correccionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correccionMenuItemActionPerformed
        this.procesoRecaudacionView = new ProcesoRecaudacionView();
        ProcesoRecaudacionController controller = new ProcesoRecaudacionController(this.procesoRecaudacionView, this);
        setNewTab(this.procesoRecaudacionView, "Proceso Recaudación");
    }//GEN-LAST:event_correccionMenuItemActionPerformed

    private void produccionConductorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produccionConductorMenuItemActionPerformed
        this.conductoresView = new ConductoresView();
        ProduccionConductorController controller = new ProduccionConductorController(this.conductoresView, this);
        setNewTab(this.conductoresView, "Producción x Conductor");
    }//GEN-LAST:event_produccionConductorMenuItemActionPerformed

    private void diasTrabajadosConductorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diasTrabajadosConductorMenuItemActionPerformed
        this.conductoresView = new ConductoresView();
        DiasTrabajadosConductorController controller = new DiasTrabajadosConductorController(this.conductoresView, this);
        setNewTab(this.conductoresView, "DT x Conductor");
    }//GEN-LAST:event_diasTrabajadosConductorMenuItemActionPerformed

    private void cincoPorcientoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoPorcientoMenuItemActionPerformed
        this.conductoresView = new ConductoresView();
        ImposicionesConductorController controller = new ImposicionesConductorController(this.conductoresView, this);
        setNewTab(this.conductoresView, "Imposiciones x Conductor");
    }//GEN-LAST:event_cincoPorcientoMenuItemActionPerformed

    private void ahorroConductorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ahorroConductorMenuItemActionPerformed
        this.conductoresView = new ConductoresView();
        AhorroConductorController controller = new AhorroConductorController(this.conductoresView, this);
        setNewTab(this.conductoresView, "Ahorros x Conductor");
    }//GEN-LAST:event_ahorroConductorMenuItemActionPerformed

    private void produccionBusMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produccionBusMenuItemActionPerformed
        this.busView = new BusView();
        ProduccionBusController controller = new ProduccionBusController(this.busView, this);
        setNewTab(this.busView, "Producción x Bus");
    }//GEN-LAST:event_produccionBusMenuItemActionPerformed

    private void produccionFlotaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produccionFlotaMenuItemActionPerformed
        this.flotaView = new FlotaView();
        ProduccionFlotaController controller = new ProduccionFlotaController(this.flotaView, this);
        setNewTab(this.flotaView, "Producción x Bus");
    }//GEN-LAST:event_produccionFlotaMenuItemActionPerformed

    private void dineroRecaudadosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dineroRecaudadosMenuItemActionPerformed
        this.dinerosRecaudadosView = new DinerosRecaudadosView();
        DinerosRecaudadosController controller = new DinerosRecaudadosController(this, dinerosRecaudadosView);
        setNewTab(this.dinerosRecaudadosView, "Dineros Recaudados");
    }//GEN-LAST:event_dineroRecaudadosMenuItemActionPerformed

    private void dinerosXProcesosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dinerosXProcesosMenuItemActionPerformed
        this.procesoGeneralView = new ProcesoGeneralView();
        ProcesoGeneralController controller = new ProcesoGeneralController(this.procesoGeneralView, this);
        setNewTab(this.procesoGeneralView, "Dineros Recaudados x Proceso");
    }//GEN-LAST:event_dinerosXProcesosMenuItemActionPerformed

    private void produccionFlotaUnidadMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produccionFlotaUnidadMenuItemActionPerformed
        this.flotaView = new FlotaView();
        ProduccionFlotaUnidadController controller = new ProduccionFlotaUnidadController(flotaView, this);
        setNewTab(this.flotaView, "Producción Flota x Unidad");
    }//GEN-LAST:event_produccionFlotaUnidadMenuItemActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.flotaView = new FlotaView();
        SaldosProduccionFlotaController controller = new SaldosProduccionFlotaController(this.flotaView, this);
        setNewTab(this.flotaView, "Saldos x Flota");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        this.busView = new BusView();
        LiquidacionBusController liquidacionBusController = new LiquidacionBusController(this.busView, this);
        setNewTab(this.busView, "Liquidación x Bus");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void planillonDescuentosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planillonDescuentosMenuItemActionPerformed
        this.mesSelectorView = new MesSelectorView();
        PlanillonDescuentosController controller = new PlanillonDescuentosController(this.mesSelectorView, this);
        setNewTab(this.mesSelectorView, "Planillón Descuentos");
    }//GEN-LAST:event_planillonDescuentosMenuItemActionPerformed

    private void flotaUnidadTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flotaUnidadTresActionPerformed
        this.flotaView = new FlotaView();
        SaldosProduccionFlotaControllerSolyMar controller = new SaldosProduccionFlotaControllerSolyMar(this.flotaView, this);
        setNewTab(this.flotaView, "Saldos Flota Millenium");
    }//GEN-LAST:event_flotaUnidadTresActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        this.flotaView = new FlotaView();
        ProduccionFlotaUnidadController controller = new ProduccionFlotaUnidadController(this.flotaView, this);
        setNewTab(this.flotaView, "Detalle x Bus x Flota");
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        this.detalleCargosView = new DetalleCargosView();
        DetalleCargosController controller = new DetalleCargosController(this.detalleCargosView, this);
        setNewTab(this.detalleCargosView, "Detalle x Cargos");
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        this.detalleAbonosView = new DetalleAbonosView();
        DetalleAbonosController controller = new DetalleAbonosController(this.detalleAbonosView, this);
        setNewTab(this.detalleAbonosView, "Detalle x Abonos");
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void conductoresSinContratoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conductoresSinContratoMenuItemActionPerformed
        this.mesSelectorView = new MesSelectorView();
        ConductoresSinContratoController controller = new ConductoresSinContratoController(this.mesSelectorView, this);
        setNewTab(this.mesSelectorView, "Conductores Sin Contrato");
    }//GEN-LAST:event_conductoresSinContratoMenuItemActionPerformed

    private void seguroCesantiaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seguroCesantiaMenuItemActionPerformed
        this.mesSelectorView = new MesSelectorView();
        SeguroCesantiaDosPuntoCuatroController controller = new SeguroCesantiaDosPuntoCuatroController(this.mesSelectorView, this);
        setNewTab(this.mesSelectorView, "Seguro 2.4%");
    }//GEN-LAST:event_seguroCesantiaMenuItemActionPerformed

    private void deudasMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deudasMenuItemActionPerformed
        this.mesSelectorView = new MesSelectorView();
        ReconocimientoDeudasController controller = new ReconocimientoDeudasController(this.mesSelectorView, this);
        setNewTab(this.mesSelectorView, "Reconocimientos de Deudas");
    }//GEN-LAST:event_deudasMenuItemActionPerformed

    private void sisMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sisMenuItemActionPerformed
        this.mesSelectorView = new MesSelectorView();
        SISController controller = new SISController(this.mesSelectorView, this);
        setNewTab(this.mesSelectorView, "SIS");
    }//GEN-LAST:event_sisMenuItemActionPerformed

    private void saldoAnteriorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoAnteriorMenuItemActionPerformed
        this.mesSelectorView = new MesSelectorView();
        SaldoAnteriorController controller = new SaldoAnteriorController(this.mesSelectorView, this);
        setNewTab(this.mesSelectorView, "Saldo Anterior");
    }//GEN-LAST:event_saldoAnteriorMenuItemActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        this.mesSelectorView = new MesSelectorView();
        SeguroCesantiaTresController controller = new SeguroCesantiaTresController(this.mesSelectorView, this);
        setNewTab(this.mesSelectorView, "Seguro 3.0%");
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void retencionJudicialMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retencionJudicialMenuItemActionPerformed
        this.mesSelectorView = new MesSelectorView();
        RetencionJudicialController controller = new RetencionJudicialController(this.mesSelectorView, this);
        setNewTab(this.mesSelectorView, "Retencion Judicial");
    }//GEN-LAST:event_retencionJudicialMenuItemActionPerformed

    private void cajaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaMenuItemActionPerformed
        this.mesSelectorView = new MesSelectorView();
        CajaCompensacionController controller = new CajaCompensacionController(this.mesSelectorView, this);
        setNewTab(this.mesSelectorView, "Caja Compensación");
    }//GEN-LAST:event_cajaMenuItemActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        this.flotaView = new FlotaView();
        DetalleLiquidacionBusFlotaController controller = new DetalleLiquidacionBusFlotaController(this.flotaView, this);
        setNewTab(this.flotaView, "Detalle x Bus x Flota");
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.flotaView = new FlotaView();
        SaldosMasLiquidacionFlotaController controller = new SaldosMasLiquidacionFlotaController(this.flotaView, this);
        setNewTab(this.flotaView, "Saldos + Liquidación");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        this.mesSelectorView = new MesSelectorView();
        MemoCargasFamiliaresController controller = new MemoCargasFamiliaresController(this.mesSelectorView, this);
        setNewTab(this.mesSelectorView, "Cargas Familiares");
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        this.terminalView = new TerminalView();
        LiquidacionTerminalController controller = new LiquidacionTerminalController(this.terminalView, this);
        setNewTab(this.terminalView, "Liquidaciones x Terminal");
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void cargasFamiliaresMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargasFamiliaresMenuItemActionPerformed
        this.mesSelectorView = new MesSelectorView();
        VoucherCargasFamiliaresController controller = new VoucherCargasFamiliaresController(this.mesSelectorView, this);
        setNewTab(this.mesSelectorView, "Voucher Cargas Familiares");
    }//GEN-LAST:event_cargasFamiliaresMenuItemActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        this.mesSelectorView = new MesSelectorView();
        DistribucionSindicatosController controller = new DistribucionSindicatosController(this.mesSelectorView, this);
        setNewTab(this.mesSelectorView, "Dist. Sindicatos");
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        this.mesSelectorView = new MesSelectorView();
        DistribucionTerminalController controller = new DistribucionTerminalController(this.mesSelectorView, this);
        setNewTab(this.mesSelectorView, "Dist. Liquidaciones +");
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        this.mesSelectorView = new MesSelectorView();
        DistribucionTerminalNegativosController controller = new DistribucionTerminalNegativosController(this.mesSelectorView, this);
        setNewTab(this.mesSelectorView, "Dist. Liquidaciones -");
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        this.mesSelectorView = new MesSelectorView();
        DistribucionCargasFamiliaresController controller = new DistribucionCargasFamiliaresController(this.mesSelectorView, this);
        setNewTab(this.mesSelectorView, "Voucher Cargas Familiares");
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        this.liquidacionVinabusView = new LiquidacionVinabusView();
        TerceraHojaController controller = new TerceraHojaController(this.liquidacionVinabusView, this);
        setNewTab(this.liquidacionVinabusView, "Tercera Hoja");
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void aportePatronalMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aportePatronalMenuItemActionPerformed
        this.mesSelectorView = new MesSelectorView();
        AportePatronalController controller = new AportePatronalController(this.mesSelectorView, this);
        setNewTab(this.mesSelectorView, "Aporte Patronal");
    }//GEN-LAST:event_aportePatronalMenuItemActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        this.mesSelectorView = new MesSelectorView();
        DetalleISTController controller = new DetalleISTController(this.mesSelectorView, this);
        setNewTab(this.mesSelectorView, "Detalle IST Grupal");
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        try {
            Map params = new HashMap();
            JasperReport jasperReport;
            InputStream in = getClass().getResourceAsStream("/jrxml/INF-Conductores.jrxml");

            jasperReport = JasperCompileManager.compileReport(in);

            Conexion con = new Conexion();

            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, params, con.getConnection());
            setNewReport(new JRViewer(jasperPrint), "Listado General de Conductores");
        } catch (JRException jre) {
            System.err.println(jre.getMessage());
        }
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        this.flotaView = new FlotaView();
        SaldosMasLiquidacionFlotaSolyMarController controller = new SaldosMasLiquidacionFlotaSolyMarController(this.flotaView, this);
        setNewTab(this.flotaView, "Saldos + Liquidación UN3");
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        this.mesSelectorView = new MesSelectorView();
        SeguroController controller = new SeguroController(this.mesSelectorView, this);
        setNewTab(this.mesSelectorView, "Metlife");
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        this.mesSelectorView = new MesSelectorView();
        SeguroInteramericaController controller = new SeguroInteramericaController(this.mesSelectorView, this);
        setNewTab(this.mesSelectorView, "Interamericana");
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        this.mesSelectorView = new MesSelectorView();
        CreditoSaludController controller = new CreditoSaludController(this.mesSelectorView, this);
        setNewTab(this.mesSelectorView, "Credito Salud");
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
        this.mesSelectorLiquidacionView = new MesSelectorlLiquidacionView();
        LiquidacionDinamicaController controller = new LiquidacionDinamicaController(this.mesSelectorLiquidacionView, this);
        setNewTab(this.mesSelectorLiquidacionView, "Liquidaciones");
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try {
            Map params = new HashMap();
            JasperReport jasperReport;
            InputStream in = getClass().getResourceAsStream("/jrxml/INF-BusxTerminal.jrxml");

            jasperReport = JasperCompileManager.compileReport(in);

            Conexion con = new Conexion();

            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, params, con.getConnection());
            setNewReport(new JRViewer(jasperPrint), "Listado Terminal x Bus");
        } catch (JRException jre) {
            System.err.println(jre.getMessage());
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporterVBView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporterVBView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporterVBView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporterVBView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ReporterVBView frame = new ReporterVBView();
                ImageIcon img = new ImageIcon("icon.png");
                frame.setTitle("Reportes Viña Bus S.A.");
                frame.setIconImage(img.getImage());
                frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
                frame.setVisible(Boolean.TRUE);
            }
        });
    }

    public JTabbedPane getTabbedPane() {
        return tabbedPane;
    }

    public JSplitPane getSplitPane() {
        return splitPane;
    }

    public JTabbedPane getReportTabbedPane() {
        return reportTabbedPane;
    }

    public void setNewReport(JComponent panel, String title) {
        this.reportTabbedPane.add(title, panel);
        this.reportTabbedPane.setSelectedComponent(panel);
        this.reportTabbedPane.setTabComponentAt(this.reportTabbedPane.getSelectedIndex(), new ButtonTabComponent(this.reportTabbedPane));
    }

    public void setNewTab(JComponent panel, String title) {
        this.tabbedPane.add(title, panel);
        this.tabbedPane.setSelectedComponent(panel);
        this.tabbedPane.setTabComponentAt(this.tabbedPane.getSelectedIndex(), new ButtonTabComponent(this.tabbedPane));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem ahorroConductorMenuItem;
    private javax.swing.JMenuItem aportePatronalMenuItem;
    private javax.swing.JMenuItem bonosFlotasMenuItem;
    private javax.swing.JMenu busesMenu;
    private javax.swing.JMenuItem cajaMenuItem;
    private javax.swing.JMenuItem cargasFamiliaresMenuItem;
    private javax.swing.JMenuItem cincoPorcientoMenuItem;
    private javax.swing.JMenu conductoresMenu;
    private javax.swing.JMenuItem conductoresSinContratoMenuItem;
    private javax.swing.JMenuItem correccionMenuItem;
    private javax.swing.JMenu descuentoMenu;
    private javax.swing.JMenuItem deudasMenuItem;
    private javax.swing.JMenuItem diasTrabajadosConductorMenuItem;
    private javax.swing.JMenuItem dineroRecaudadosMenuItem;
    private javax.swing.JMenuItem dinerosXProcesosMenuItem;
    private javax.swing.JMenuItem errorCodigoMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu extrasMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem flotaUnidadTres;
    private javax.swing.JMenu flotasMenu;
    private javax.swing.JMenu guiasMenu;
    private javax.swing.JMenuItem istMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem planillonDescuentosMenuItem;
    private javax.swing.JMenuItem planillonImposicionMenuItem;
    private javax.swing.JMenuItem produccionBusMenuItem;
    private javax.swing.JMenuItem produccionConductorMenuItem;
    private javax.swing.JMenuItem produccionFlotaMenuItem;
    private javax.swing.JMenuItem produccionFlotaUnidadMenuItem;
    private javax.swing.JMenu remuneracionesMenu;
    private javax.swing.JTabbedPane reportTabbedPane;
    private javax.swing.JMenuItem retencionJudicialMenuItem;
    private javax.swing.JMenuItem saldoAnteriorMenuItem;
    private javax.swing.JMenuItem segundasImposicionesMenuItem;
    private javax.swing.JMenuItem seguroCesantiaMenuItem;
    private javax.swing.JMenuItem sisMenuItem;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
    private ProcesoRecaudacionView procesoRecaudacionView;
    private ConductoresView conductoresView;
    private BusView busView;
    private FlotaView flotaView;
    private DinerosRecaudadosView dinerosRecaudadosView;
    private ProcesoGeneralView procesoGeneralView;
    private MesSelectorView mesSelectorView;
    private LiquidacionVinabusView liquidacionVinabusView;
    private DetalleCargosView detalleCargosView;
    private DetalleAbonosView detalleAbonosView;
    private TerminalView terminalView;
    private MesSelectorlLiquidacionView mesSelectorLiquidacionView;
}
